-- 增加年级、专业、班级字段
ALTER TABLE users ADD COLUMN IF NOT EXISTS grade VARCHAR(16);
ALTER TABLE users ADD COLUMN IF NOT EXISTS major VARCHAR(64);
ALTER TABLE users ADD COLUMN IF NOT EXISTS class VARCHAR(32);
-- 可根据实际需要调整字段长度
